### PR TITLE
Updated to include the panchromatic bands from both LS7 and LS8. Remo…

### PR DESCRIPTION
**Pull request by sixy6e**
…ved old reference to 'brdf_wavelength', which is replaced by 'brdf_dataset'. Relabelled 'brdf_dataset' to 'brdf_datasets' and the value should now be a list of dataset names.

### CODE REVIEW

**Comment by sixy6e** [comment]
@uchchwhash 

What are your initial thoughts on this?

My initial idea is to loop over 'brdf_datasets' and build up 'n' mean values for 'n' in 'brdf_datasets'.

We need to either extend _constants.BRDFParameters_ to include _ALPHA-1_ and _ALPHA-2_ or split into separate enums, such as:

* BRDFModelParameters
    1. ISOMETRIC
    2. VOLUMETRIC
    3. GEOMETRIC
* BRDFDirectionalParameters (or BRDFDerivedParameters)
    1. ALPHA-1
    2. ALPHA-2

Once the acquisition footprint means are determined for each of _ISO, VOL, GEO_ for each BRDF dataset_name in 'brdf_datasets', we then create _alpha1_ and _alpha2_ for each BRDF dataset_name in 'brdf_datasets'.  Then average all items in _alpha1_ and all items in _alpha2_.

i.e.
sum(alpha) / len(brdf_datasets)

So for singular brdf dataset lookups, the average will simply be alpha / 1

**Comment by uchchwhash** [comment]
I think this is great, but let me fix the BRDF collection 6 branch before I merge this.

**Comment by sixy6e** [comment]
I've updated the tests and added a couple more to test the loading of the pan band for LS7 and LS8.  But looks like some conflicts have arisen. WIll take a look next week.

**Review by uchchwhash — APPROVED** [review]
Let's merge it!

**Pull request merged**
