### PR TITLE
Auxiliary 2 hdf5

### PR DESCRIPTION
**Pull request by sixy6e**
Enables reading of the reformatted auxiliary datasets.

### CODE REVIEW

**Review by uchchwhash — APPROVED** [review]
Should I make use of BRDF tiers in `brdf.py` too?

**Comment by sixy6e** [comment]
Yeah, if they help.  I was using it to strictly classify and compare.

**Comment by ASVincent** [comment]
Just need to rebase from develop and add the dataset_path/filename to the current_h5_metadata method :)

**Comment by sixy6e** [comment]
Will close as the work has been merged under #281

**Pull request merged**
